latent_dim: 32
batch_size: 32
lr: 1.e-4
lr_schedule_rate: 1

kl_lambda: 0.3

save_every: 50
num_epochs: 10001

feature_noise_power: NULL
feature_noise_decay: NULL

data_version: 'data_v4'
pad_range: [-3, 5]
time_range: [-7, 9]
scaler: 'logarithmic'
encoder_type: 'conv'

architecture:
    decoder:
        - block_type: 'fully_connected'
          arguments:
            units: [32, 64, 64, 64, 128]
            activations: [
                'elu', 'elu', 'elu', 'elu',
                " (
                    lambda x,
                           shift=0.01,
                           val=np.log10(2),
                           v0=np.log10(2) / 10: (
                        tf.where(
                            x > shift,
                            val + x - shift,
                            v0 + tf.keras.activations.elu(
                                x,
                                alpha=(v0 * shift / (val - v0))
                            ) * (val - v0) / shift
                        )
                    )
                )"
            ]
            kernel_init: 'glorot_uniform'
            input_shape: [37,]
            output_shape: [8, 16]
            name: 'decoder'

    encoder:
        - block_type: 'connect'
          arguments:
            vector_shape: [5,]
            img_shape: [8, 16]
            vector_bypass: False
            concat_outputs: True
            name: 'encoder_tail'
            block:
              block_type: 'conv'
              arguments:
                filters: [16, 16, 32, 32, 64, 64]
                kernel_sizes: [3, 3, 3, 3, 3, 2]
                paddings: ['same', 'same', 'same', 'same', 'valid', 'valid']
                activations: ['elu', 'elu', 'elu', 'elu', 'elu', 'elu']
                poolings: [NULL, [1, 2], NULL, 2, NULL, NULL]
                kernel_init: glorot_uniform
                input_shape: NULL
                output_shape: [64,]
                dropouts: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
                name: encoder_conv_block
        - block_type: 'fully_connected'
          arguments:
            units: [256, 128, 64]
            activations: ['elu', 'elu', NULL]
            kernel_init: 'glorot_uniform'
            input_shape: [69,]
            output_shape: [2, 32]
            name: 'encoder_head'
