latent_dim: 64
batch_size: 32
lr: 1.e-3
lr_schedule_rate: 0.999

kl_lambda: 2

save_every: 40
num_epochs: 4001

feature_noise_power: NULL
feature_noise_decay: NULL

data_version: 'data_v4'
pad_range: [-3, 5]
time_range: [-7, 9]
scaler: 'logarithmic'
encoder_type: 'conv'

architecture:
    decoder:
        - block_type: 'fully_connected'
          arguments:
            units: [64, 128, 256, 128]
            activations: [
                'elu', 'elu', 'elu',
                " (
                    lambda x,
                           shift=0.01,
                           val=np.log10(2),
                           v0=np.log10(2) / 10: (
                        tf.where(
                            x > shift,
                            val + x - shift,
                            v0 + tf.keras.activations.elu(
                                x,
                                alpha=(v0 * shift / (val - v0))
                            ) * (val - v0) / shift
                        )
                    )
                )"
            ]
            kernel_init: 'glorot_uniform'
            input_shape: [64,]
            output_shape: [8, 16]
            name: 'decoder'

    encoder:
        - block_type: 'conv'
          arguments:
            filters: [8, 8, 16, 16, 32, 32, 64, 128]
            kernel_sizes: [3, 3, 3, 3, 3, 3, 3, 2]
            paddings: ['same', 'same', 'same', 'same', 'same', 'same', 'valid', 'valid']
            activations: ['elu', 'elu', 'elu', 'elu', 'elu', 'elu', 'elu', 'elu']
            poolings: [NULL, [1, 2], NULL, NULL, NULL, 2, NULL, NULL]
            kernel_init: glorot_uniform
            input_shape: [8, 16, 1]
            output_shape: [2, 64]
            dropouts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
            name: encoder_conv_block     
